services:
  - type: web
    name: testing-agent-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: CORS_ORIGINS
        value: https://testing-agent-skheni.vercel.app,http://localhost:3000